language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: 0sYpRsEuLILYUA0Y+khetLr6Z6yX0O+M69EAv/eVPKo9VY1+LfE0TyI1D+9M+loW91AMfemtLnD94OmPTVKxYby+4nLleRxveXdwNNowvKyb1956LHqsShk9XXPOFtSBqKjJDppqlt2Jy9KgNM7Qbr8BgTiFyU1IiYfE4rSg9mxeL5DtouwqxV7GMyPZn1NaLMroAMKiujuDSgOfgJFsnVFWgNbpQQknH/ww0+Q+LlNJkSr5Q1nzT5aziE5Y+YRon7YBmOyX2Zbqxws9+QwygiVYiGnG9W6HrsMzd3cwac/U2ZjMbOp13VrPywk7RINDH7ugpyQqkGwTUQ0oQbEAJ1z0mVCv5HY+ergqL9fUPiCPA9HMUl1xbNjKB/d68TK3abXMGq8/IIMYvAGxAJQrUWS91KYSNyDKv/Aq1LWR7djBCgOUWQ1dZO3wnMr6pbD8JHwh1oY+W/PTzZhedEIe6XdLJpw0pojGXFCx5vM5Zdyq2i7sD4TvjYuQJiYIwJ0wfFUas5W51KZ1m3+S/avUvyB6gPF8TBt33lU1B60vr5JMESRqhCcGag1Fn+bjm5k2OvuMJBNX8L6msCIHyaEYtgc8ufmFSSRKJavNQfROAirK/yc+gi6VRdB6t0QyPDC+0atxkbli0FQzcXQ83auJfKFkEVmWoNzN6iDoHhA4Inw=
  app: Symphony
  on:
    repo: AndrewPark9517/Symphony
