language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: dsIgj7yvNaWJQuJ6toENHU7qX1dIFKFxUV/yi9inpG+Tzms++jBEpmL8rU+iGbs/FzMgDymDZ6Oq4UVfu9NvMLu7TsqrjyVp3thQeRfLlqm9sY8DmLzcQ3BZR0ZLmlPYSwG6R4OvHZh/LU4xM+pZZxLrZoIdiMyElpnSwZzM1tUBFzVxCh7BCpc7QeEg6MxB83ml0iOIurwQHP+kd/Pa3j6nCZf9uOACa/OmDlJv7yjuZRosM6/+Mn3beOpxJzzAEb8adFhp617WwvA8ol6G7B4nF1IKDkGGj6IBgE2tR/T3zwu0lmcr+ZXz5+Q/GmvuVMQgAVZlyqjOAe2lsGa/nixTv8Nl/VxbJqXKDjXkzgNDDsuKpfbsHW6Vn6O+auje2NPZa/kVEcXh2b9Kln6ke2zkOECErBZnPzg/2cr4kzx1s0nNVCNy9s/71Wx500RJdMfhu78etFyKt/9vBMGYkksOUygoYUT6LeNYLUEaygnsNhwphg+TyN0xAh02/iblPAUmHGuMdJufHcW3dnB0t+OAKLE9cmxeZiBqPda7MKaQyuOGKQyynKXxVMO9ZIFk0sEaQf7CZge2JNQiW04gS6LpJh5fWXCaZHUsIVStLrNgliAXdA7nlCpVgEQ9SnOs7NK3ygKMPZdDfMvxvooDGDIiBxWdj7SLwMfpsUD6Ijo=
  app: fast-escarpment-54397
  on:
    repo: AndrewPark9517/Symphony
