language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: mYREM2iTAI/rBv/UhK6mnys6bUHqLqj8njCkNrGOLNlXBHGD0Xq7jGezjyh5t0sX/D5AjFoOxGXnyMrFuoyr3Ib2TaYvN8p9ouWdU+XeenVxOvdzqs8TY4mZNEky6Gv+BBnx7rZdp6W/f9yz2Gn62IlU3WSJOsu0BVwMOe1IeP0nB7LXYdYQiW23VaYMdyzs1oq/51LI8Nt5Zt8hZY+mPcItL080J5MkfcGo85kPSZmDFvBIGyiE86UfVp5Cf/Odstfr/0WGUb6dihVeEHgvJzKYIuq5BcZvZBINpntwleQsU8lRjG6F4I2Mz5H5/7us0dFkn9BsEdvhRYbDgQVvthwemc7/OytNJOhnynA9v05o/kCpsy2j8DH0JJA5kE5WnseMH4dZsTtvEesSHTe/nYhoUmckt3frs7/Y/NrUQsPk6FukKdd1cKsXRSozgJfVi4wsHEINIyQu2fO2CsSu/iRBpgxcQHf9z/nW5dUUTZ6AMk8HB4Hh8vuTtXUzoQf6qPkp6w7bx/AN8GZ/y2yD2UZ8rtoJ0+5RPc2PetRVeW/ZRdmI+lqx83vekDTok1utBeySNMFC1ZnUibbqHRGq4Pc6S2LNP1UskZxw4411TuWg6PxJRXR/S8c7Kbbx3ni8udISgvjsa5KprNz/rNPH3+c6e9uPAM93lQRAHLKieDA=
  app: Symphony
  on:
    repo: AndrewPark9517/Symphony
