language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: uBllP0w7+oDLeh7B+GkmV5v1cniHWXeLMvHkh7zB6Fgs8JP8/DRR0M/Fxg/TgGmG52l7WP2MIzDZUIPlJ8nJcfF/4AQ+JZTi9D3cJDN+Eh3H8iXnMAokHWOERPsrC4eLm3pjI6RwjqaDy+AExNjx+rh7xOU49oS7pe+aoeEuPYr62dqkPIBGQwD9gylcwKKaOFMfy4gLk2Mn0SkDRxAq1Ivnr5Gl+XEU6GCRItkViXvFZBKyD17l/jW3FYjfYpT+ZPW5Q3EiQe8T2BCt2hBI/uRwj8XaQarSi0W4r7rFWVTRZ4O/31D2FNqfjCgiWhgPD2gnZgEe04IsWo1qgd7OB4C4nMUchE+htl/b6GvnlSXE+AvimJ8AL89j1ZjFsWH23L0YPdXqGRsDwF4HLHn1r0Fd4zHGY2rMstFlw+c/0GSFSj789tJM2JNVyI+b+sAjZPIqXqbbKhp9ZG/oXbPqpA2eLC25NMUfNC8Vcg4/kjOIPkiojbGS9UuyvlAoX0a4brkdPKNIAPXkR00Tl5tNoSsfUAUw/n5RxYmDiqJHDB66G2HEACux2p16fXldhDXZNCCCOV/zTB1BuuK1snRuHip+rh5aO3MAhW/TwpxzLgTUMh98wss2zAn9+klh475gPJ9/f+rJ/St+MIjtqAASdp9zUoPk9Z/86sMjuFAb2Rk=
  app: Symphony
  on:
    repo: AndrewPark9517/Symphony
