language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: katCovRq5I5OVf4WXXK8LPcCNREFSLFD3R3uZjK2a5X0aQILCsuntobgMF9nG2SWhVc6AEs/2IkXUDBibSIQ3IJd3NyHwA/LrgK4kOneTdRA2xa+oA67oAvXmKAUkXv8LTiM64yeK0yro+vTLSgdwGbbNA9lAOC8Wu5GPkQSuPzojJzWvy8R49/kat6uI4dIvSmdHaqMC4C25xZDRIbK+ma6fdcjeQ4Ep0kQr5ILPTsYypVAava2PXrJ7EeUYAENNa6BF0YG9oMeWMncefWt/cAGdzwqlvWHKkmJ9xnUEIykWRrbsK51IMEBLmf1OkP5U3d5XBsVI4JUENunKDdEVyn0qBhVlOjllB83oy3v5pCvgrdHR8MQK/yhJ+88flyOVZc+J/YJR7Eu/jsTLo8kJWb4vOFemPiI4EOHnwIWR6KeLX1fpdjmTMICF6yYSFRHS4EDYWXlLLhf3zbyEBnAfe+vbPmar49JRNXdA3Ib+qMT7lXykOQoqh9r5tMw3vE+AuoI/dtbbQlWHIavz1Tt4o9HcpqdrQEgujP/zyGYG++9ksdnJKuIbaCDv+t1hPyDoAIEmU/LLLQB8mUmKFglpbSePbMbjs/ckX0MeN85VhXydhbyLlGqePM1jzCY7fWETqXM8eVWtg/oE9JwjzfAV8rz8ytp76+ZAvNbSFSdM/c=
  app: Symphony
  on:
    repo: AndrewPark9517/Symphony
