language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: rRq9GNBOlz2j+IBKlfCq6Y5qiY11FuV81CR6r4KySoz01HOXlh6L8RpnB0d89mWbUpTe8/byDQxtCi3a+9W9PbwVXTPoyprM1+cwi6FtSeaVS4IF7KJB++fbMgFXDprFktnzA3J1NyL2/VZ757kfs3voLE0KS56DCcm1m4+iuHLeKH+KR9BUuaUGRynd8osbMM3UVTWS9ZClE8m72F0kRibx+IAUf4Q2zCUZsM62AhuCpegLoKP0ZunOq8SWjuhx8T7zPJZ5axWnMt6zRjF8yeZbqvT28xhlcLKS2q1uol6FELYKy0qHirLjL1Y+vLr5SOM60I3ilj8do8gVqPmXP4Pbrg+dHFvjim5JzoGzTdR0xLD0UysmISy3PTvS8USB/bP6vo8g6hg5G8pEOk09YOL38B4J3keR+qiDtyQ23ubbc1NktvKFTiQQXaJF19E4w8VRaf0F+kzx2MVsACH5DDBy2w41xlVqiCUQJZScbAwpTPK93bI3zRyPPCwaIbJL7Lmuf8q+lfSliOCgD+wid7ejeHInJSr+U936UXc395n0kKjtGlmIBoE0dLd2yv2phRQiMKd9+mrWdH8ziI4HWIp/4ZnEuQaMtNLRW+5RHknlIXTbccJscMMNL60fMnuWm9wwxy+GhbBQAn+i3HgwS/cHVqBvu0Bv30Otf11oAS0=
  app: Symphony
  on:
    repo: AndrewPark9517/Symphony
